version: '3'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'pix'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      URL_DATABASE: 'jdbc:mysql://localhost:3306/pix'
    ports:
      - '3306:3306'
    expose:
      - '3306'