micronaut:
  application:
    name: pix
datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: 'password'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
